# Introducción a Tensores en PyTorch

Operaciones aritméticas básicas.

In [1]:
import torch

a=torch.tensor([1.,2.,3.])
b=torch.tensor([4.,5.,6.])
print(a)
print(b)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [2]:
# Suma
a+b

tensor([5., 7., 9.])

In [3]:
# Resta
a-b

tensor([-3., -3., -3.])

In [4]:
# Multiplicación elemento a elemento
a*b

tensor([ 4., 10., 18.])

In [5]:
# División
a/b

tensor([0.2500, 0.4000, 0.5000])

In [6]:
# Escalares
2*a+1

tensor([3., 5., 7.])

In [7]:
print(a.sum())
print(a.mean())

tensor(6.)
tensor(2.)


In [8]:
A=torch.tensor([[1.,2.],[3.,4.]])
B=torch.tensor([[5.,6.],[7.,8.]])
A@B

tensor([[19., 22.],
        [43., 50.]])

In [9]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [13]:
x=torch.tensor(3.5, requires_grad=True)
y=torch.tensor(1.5, requires_grad=True)
z=x*+2+y**2-4*x*y*torch.cos(3*x+2*y)
print('z=',z)
z.backward()
print('dz/dx=',x.grad, ', dz/dy=',y.grad)

z= tensor(-3.2433, grad_fn=<SubBackward0>)
dz/dx= tensor(49.0689) , dz/dy= tensor(28.4301)
